<style>
#dropOverlay{
    position:fixed;
    top:0;
    left:0;
    right:0;
    bottom:0;
    background:rgba(0,0,0,0.4);
    display:none;
    align-items:center;
    justify-content:center;
    z-index:9999;
}

.dropBox{
    background:white;
    padding:40px;
    border-radius:8px;
    font-size:20px;
}
</style>